In [3]:
#문항 1

import numpy as np

scores_1d = [88, 92, 79, 95,
             75, 68, 82, 70,
             92, 99, 95, 88,
             60, 72, 65, 58,
             85, 80, 78, 90]

scores = np.array(scores_1d).reshape(5, 4)
scores = np.random.randint(50, 101, size= 20).reshape(5, 4)


In [10]:
print("1.", scores, scores.shape, scores.ndim, scores.size, scores.dtype)
print("2. 학생평균", scores.mean(axis=1), "과목평균", scores.mean(axis=0))
print("3. 최고점", scores.max(), "위치:", np.unravel_index(scores.argmax(), scores.shape))
print("4. 전체평균", scores.mean(), "표준편차", scores.std(), "분산", scores.var())

m = scores.mean(axis=1) >= 80
print("5. 80점 이상의 학생 수", m.sum(), "성적", scores[m])
print("6. 90점 이상의 개수", (scores >= 90).sum(), "100점이 있는가.", (scores >= 100).any(), "60점 이상", (scores >= 60).all())
print("7. 등급", np.select([scores >= 90, scores >= 80], ['A', 'B'], default = ['C']  ))
      

1. [[50 93 54 81]
 [56 62 61 61]
 [79 77 58 81]
 [82 80 77 62]
 [77 72 54 92]] (5, 4) 2 20 int32
2. 학생평균 [69.5  60.   73.75 75.25 73.75] 과목평균 [68.8 76.8 60.8 75.4]
3. 최고점 93 위치: (np.int64(0), np.int64(1))
4. 전체평균 70.45 표준편차 12.78465877526655 분산 163.44750000000002
5. 80점 이상의 학생 수 0 성적 []
6. 90점 이상의 개수 2 100점이 있는가. False 60점 이상 False
7. 등급 [['C' 'A' 'C' 'B']
 ['C' 'C' 'C' 'C']
 ['C' 'C' 'C' 'B']
 ['B' 'B' 'C' 'C']
 ['C' 'C' 'C' 'A']]


In [11]:
#문항 2
import numpy as np

np.random.seed(2024)
img = np.random.randint(0, 256, size = (8, 8))

In [12]:
print("1. 원본이미지", img)

1. 원본이미지 [[136 250  96 128  27  36 190 183]
 [ 41 127 193  60 227  74  66 224]
 [165 252 241 158 111 247 202 110]
 [ 95 111  11  28  91  39  54 114]
 [183  73 102 218 244  42  31  97]
 [150  27  86 119  69 157  61 243]
 [ 54 132  57  86  54 254 148 126]
 [136  18  97  90 202 135 176 232]]


In [15]:
print("2. 이미지 정중앙의 4×4 영역", img[2:6, 2:6])

2. 이미지 정중앙의 4×4 영역 [[241 158 111 247]
 [ 11  28  91  39]
 [102 218 244  42]
 [ 86 119  69 157]]


In [16]:
print("3. 짝수 번째 행", img[::2])

3. 짝수 번째 행 [[136 250  96 128  27  36 190 183]
 [165 252 241 158 111 247 202 110]
 [183  73 102 218 244  42  31  97]
 [ 54 132  57  86  54 254 148 126]]


In [18]:
bin_img = np.where(img >= 128, 255, 0)

print("4. 이진화 배열:", bin_img)

4. 이진화 배열: [[255 255   0 255   0   0 255 255]
 [  0   0 255   0 255   0   0 255]
 [255 255 255 255   0 255 255   0]
 [  0   0   0   0   0   0   0   0]
 [255   0   0 255 255   0   0   0]
 [255   0   0   0   0 255   0 255]
 [  0 255   0   0   0 255 255   0]
 [255   0   0   0 255 255 255 255]]


In [19]:
print("5. 흰색 픽셀 개수:", (bin_img == 255).sum(), "/ 검은색 픽셀 개수:", (bin_img == 0).sum())

5. 흰색 픽셀 개수: 28 / 검은색 픽셀 개수: 36


In [20]:
left = img[:, :4]
right = img[:, 4:]
print("6. 좌측 절반:", left)
print("우측 절반:", right)

6. 좌측 절반: [[136 250  96 128]
 [ 41 127 193  60]
 [165 252 241 158]
 [ 95 111  11  28]
 [183  73 102 218]
 [150  27  86 119]
 [ 54 132  57  86]
 [136  18  97  90]]
우측 절반: [[ 27  36 190 183]
 [227  74  66 224]
 [111 247 202 110]
 [ 91  39  54 114]
 [244  42  31  97]
 [ 69 157  61 243]
 [ 54 254 148 126]
 [202 135 176 232]]


In [24]:
flipped_img = np.concatenate((right, left), axis=1)
print("7. 좌우 반전 이미지:", flipped_img)

7. 좌우 반전 이미지: [[ 27  36 190 183 136 250  96 128]
 [227  74  66 224  41 127 193  60]
 [111 247 202 110 165 252 241 158]
 [ 91  39  54 114  95 111  11  28]
 [244  42  31  97 183  73 102 218]
 [ 69 157  61 243 150  27  86 119]
 [ 54 254 148 126  54 132  57  86]
 [202 135 176 232 136  18  97  90]]


In [ ]:
flat_img = img.flatten()
print("8. 1차원 앞 10개 값:", flat_img[:10], "/ shape:", flat_img.shape)


8. 1차원 앞 10개 값: [136 250  96 128  27  36 190 183  41 127] / shape: (64,)


In [26]:
masked_pixels = img[img >= 128]
print("9. 128 이상 픽셀 개수:", masked_pixels.size, "/ 평균값:", masked_pixels.mean())

9. 128 이상 픽셀 개수: 28 / 평균값: 193.07142857142858


In [ ]:
#문항 3
sales = np.array([[120,  80,  45,  60],     # A지점
                  [200, 150,  90,  30],     # B지점
                  [ 75,  60, 120,  95]])    # C지점
price = np.array([1500, 3000, 5000, 2000])  # 제품 1~4 단가


In [15]:
#문항 3
import numpy as np

sales = np.array([[120,  80,  45,  60],     # A지점
                  [200, 150,  90,  30],     # B지점
                  [ 75,  60, 120,  95]])    # C지점
price = np.array([1500, 3000, 5000, 2000])  # 제품 1~4 단가

In [7]:
revenue = sales * price
print("1. 제품별 매출액:", revenue)

1. 제품별 매출액: [[180000 240000 225000 120000]
 [300000 450000 450000  60000]
 [112500 180000 600000 190000]]


In [8]:
total_revenue = sales @ price  
product_total_sales = sales.sum(axis=0)
print("2. 지점별 총매출:", total_revenue, "/ 제품별 총판매량:", product_total_sales)


2. 지점별 총매출: [ 765000 1260000 1082500] / 제품별 총판매량: [395 290 255 185]


In [ ]:
mean_sales = sales.mean(axis=0)
diff = sales - mean_sales
print("3. 평균 대비 편차 행렬:", diff)


3. 평균 대비 편차 행렬: [[-11.66666667 -16.66666667 -40.          -1.66666667]
 [ 68.33333333  53.33333333   5.         -31.66666667]
 [-56.66666667 -36.66666667  35.          33.33333333]]
7. 최고 매출 지점 인덱스: 1 / 누적 매출: [ 765000 2025000 3107500]


In [ ]:
norm = (sales - sales.mean(axis=1, keepdims=True)) / sales.std(axis=1, keepdims=True)
print("4. 정규화 결과:", norm)
print("   행별 평균:", norm.mean(axis=1), "/ 행별 표준편차:", norm.std(axis=1))


4. 정규화 결과: [[ 1.55440457  0.13323468 -1.11028898 -0.57735027]
 [ 1.29337197  0.50951017 -0.43112399 -1.37175815]
 [-0.55555556 -1.22222222  1.44444444  0.33333333]]
   행별 평균: [ 0.00000000e+00  0.00000000e+00 -4.16333634e-17] / 행별 표준편차: [1. 1. 1.]


In [12]:
print("5. 전치행렬:\n", sales.T, "/ shape:", sales.T.shape)

5. 전치행렬:
 [[120 200  75]
 [ 80 150  60]
 [ 45  90 120]
 [ 60  30  95]] / shape: (4, 3)


In [11]:
A = sales[:, :3]
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
identity_check = A @ inv_A
print("6. 행렬식:", det_A)
print("   역행렬:", inv_A)
print("   단위행렬 확인:", identity_check)

6. 행렬식: 165749.9999999999
   역행렬: [[ 0.0760181  -0.04162896  0.00271493]
 [-0.1040724   0.06651584 -0.01085973]
 [ 0.00452489 -0.00723982  0.01206637]]
   단위행렬 확인: [[ 1.00000000e+00 -7.65880415e-16 -4.68375339e-17]
 [-4.92661467e-16  1.00000000e+00 -9.36750677e-17]
 [ 1.94289029e-16 -2.28983499e-16  1.00000000e+00]]


In [14]:
max_idx = total_revenue.argmax()
cumulative_revenue = np.cumsum(total_revenue)
print("7. 최고 매출 지점 인덱스:", max_idx, "누적 매출:", cumulative_revenue)

7. 최고 매출 지점 인덱스: 1 누적 매출: [ 765000 2025000 3107500]
